Added new local module to extract only relevant annotation statistics
sanger-tol/genomenote pull request #136
Opened 2024-08-29 10:28 UTC by SandraBabirye

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

2024-08-29 10:31 UTC, SandraBabirye commented
Hi @BethYates and @tkchafin  kindly help me run this code your end and see if its running using 
nextflow run main.nf -profile test,singularity --workflow ANNOTATION_STATS
Thank you

2024-08-29 11:49 UTC, tkchafin commented
I'm getting this error, is that what you are getting now as well: 

```
ERROR ~ Error executing process > 'SANGERTOL_GENOMENOTE:GENOMENOTE:ANNOTATION_STATS:EXTRACT_ANNOTATION_STATISTICS_INFO (1)'

Caused by:
  Process `SANGERTOL_GENOMENOTE:GENOMENOTE:ANNOTATION_STATS:EXTRACT_ANNOTATION_STATISTICS_INFO` input file name collision -- There are multiple input files for each of the following file names: GCF_949628265.1_ieCloDipt1.1_genomic.gff3.stats.txt
```

2024-08-29 11:51 UTC, tkchafin commented
I'll take a look 👍

2024-08-29 12:30 UTC, tkchafin requested changes
I have tested with these changes and it seems to work -- it was really close, just needed to clean up a bit how files were named and how they were passed into the final `EXTRACT_` process

2024-08-29 12:30 UTC, tkchafin commented on bin/extract_annotation_statistics_info.py
Need to change the permission on this `chmod 777`

2024-08-29 12:30 UTC, tkchafin commented on conf/modules.config
>              mode: params.publish_dir_mode,
Suggest removing the publishDir directive here, since we extract all the bits we want and place into the `csv`

2024-08-29 12:30 UTC, tkchafin commented on conf/modules.config
>      withName: AGAT_SPSTATISTICS {
remove publishDir for `AGAT_SPSTATISTICS` as well?

2024-08-29 12:30 UTC, tkchafin commented on conf/modules.config
>          publishDir = [
The error you are getting with "input file name collision" is because the files created by this process and the other `AGAT_` process have the same name, because they are named with `meta.id`. this is confusing, because you are *publishing* them with different names, however what is being passed to your `EXTRACT_` process is the original file (found in `work/../...`), and those have the exact same names. We can change how that file is named here:

```suggestion
        ext.prefix = { "${meta.id}_sqstats" }
```

2024-08-29 12:30 UTC, tkchafin commented on conf/modules.config
>          publishDir = [
Same here

```suggestion
        ext.prefix = { "${meta.id}_spstats" }
```

2024-08-29 12:30 UTC, tkchafin commented on conf/modules.config
> +            saveAs: { filename -> filename.equals('versions.yml') ? null : filename }
```suggestion
                        saveAs: { filename -> filename.equals('versions.yml') ? null : 'extracted_annotation_statistics.csv' },

```

2024-08-29 12:30 UTC, tkchafin commented on modules/local/extract_annotation_statistics_info.nf
> +    tuple val(meta), path(other_stats)
```suggestion
    tuple val(meta), path(basic_stats), path(other_stats)
```

2024-08-29 12:30 UTC, tkchafin commented on modules/local/extract_annotation_statistics_info.nf
> +    tuple val (meta), path("${meta.id}.csv") , emit: csv
```suggestion
    tuple val (meta), path("*.csv") , emit: csv
```

2024-08-29 12:30 UTC, tkchafin commented on subworkflows/local/annotation_statistics.nf
>      versions = ch_versions                       // channel: [ versions.yml ]
```suggestion
    stats       = EXTRACT_ANNOTATION_STATISTICS_INFO.out.csv  // channel: [ csv ]
    versions    = ch_versions                                 // channel: [ versions.yml ]
```

2024-08-29 12:30 UTC, tkchafin commented on subworkflows/local/annotation_statistics.nf
> +    ch_versions = ch_versions.mix( EXTRACT_ANNOTATION_STATISTICS_INFO.out.versions.first() )
```suggestion
    EXTRACT_ANNOTATION_STATISTICS_INFO(
        AGAT_SQSTATBASIC.out.stats_txt
        | join(AGAT_SPSTATISTICS.out.stats_txt)
    )
    ch_versions = ch_versions.mix( EXTRACT_ANNOTATION_STATISTICS_INFO.out.versions )
```

2024-08-29 12:30 UTC, tkchafin commented on conf/base.config
Likely need to do some experimentation and see how these memory values scale as a function of file size (see examples in other processes)

2024-08-29 12:31 UTC, tkchafin commented on conf/modules.config
>          publishDir = [
Also note this is assuming removal of the full publishDir block for both of the nf-core AGAT processes

2024-08-29 12:31 UTC, tkchafin commented on conf/modules.config
>          publishDir = [
same here

2024-08-29 12:31 UTC, tkchafin commented on conf/modules.config
> +            saveAs: { filename -> filename.equals('versions.yml') ? null : filename }
Since we only expect one file, we can give it an informative name here?

2024-08-29 12:32 UTC, tkchafin commented on modules/local/extract_annotation_statistics_info.nf
> +    tuple val(meta), path(other_stats)
Because the meta is identical in both cases, I combined the inputs here, but it could be done either way (just remove the `.join` in the sub workflow if keeping them with separate `meta` here

2024-08-29 14:29 UTC, SandraBabirye commented on subworkflows/local/annotation_statistics.nf
> +    ch_versions = ch_versions.mix( EXTRACT_ANNOTATION_STATISTICS_INFO.out.versions.first() )
I am inquiring using the join with have the individual files read in by the python script

2024-08-29 14:50 UTC, tkchafin commented on subworkflows/local/annotation_statistics.nf
> +    ch_versions = ch_versions.mix( EXTRACT_ANNOTATION_STATISTICS_INFO.out.versions.first() )
The join just changes how they are passed. You can pass them separately: 
```
EXTRACT_ANNOTATION_STATISTICS_INFO(
        AGAT_SQSTATBASIC.out.stats_txt, 
        AGAT_SPSTATISTICS.out.stats_txt
    )
```

In this case they both have meta (which is just [id: <gff file>]) and will need to be read in `EXTRACT_ANNOTATION...` like this: 

```
    input:
     tuple val(meta), path(basic_stats) 
     tuple val(meta2), path(other_stats) 
```

Or you can join them (which by default will look at the first item, which is the `meta` list)
```
EXTRACT_ANNOTATION_STATISTICS_INFO(
        AGAT_SQSTATBASIC.out.stats_txt. join(AGAT_SPSTATISTICS.out.stats_txt)
    )
```

This makes a new structure like [[id: <gff_file>], path1, path2] which is read  in `EXTRACT_ANNOTATION...` like this: 

```
    input:
     tuple val(meta), path(basic_stats), path(other_stats) 
```

Either way will work, I'm not sure which version is considered "best practice".

2024-08-29 15:03 UTC, SandraBabirye commented on subworkflows/local/annotation_statistics.nf
> +    ch_versions = ch_versions.mix( EXTRACT_ANNOTATION_STATISTICS_INFO.out.versions.first() )
Okay kindly also have a look at the output file name i keep getting an error of no varriable output file in the modules file

2024-09-02 15:40 UTC, BethYates commented on subworkflows/local/annotation_statistics.nf
> +    ch_versions = ch_versions.mix( EXTRACT_ANNOTATION_STATISTICS_INFO.out.versions.first() )
You need to define prefix and output file within the script section so it should be:

```
    script:
    def prefix = task.ext.prefix ?: meta.id
    def output_file = "${prefix}.csv"
```

2024-09-02 16:12 UTC, BethYates commented on bin/extract_annotation_statistics_info.py
Did you commit the file after you changed permissions @SandraBabirye? When I tried running the pipeline this script didn't have the correct permissions

2024-09-03 16:25 UTC, SandraBabirye commented on bin/extract_annotation_statistics_info.py
Yes @BethYates  i did .

2024-09-03 18:05 UTC, SandraBabirye commented on conf/base.config
Hi @tkchafin  I checked the the 'execution timeline file' and thats what it showed as the memory usage for the two processes.
SANGERTOL_GENOMENOTE:GENOMENOTE:ANNOTATION_STATS:AGAT_SPSTATISTICS (GCF_949628265.1_ieCloDipt1.1_genomic.gff3)    - 1m 51s / 2.4 GB
SANGERTOL_GENOMENOTE:GENOMENOTE:ANNOTATION_STATS:AGAT_SQSTATBASIC (GCF_949628265.1_ieCloDipt1.1_genomic.gff3)     - 17.5s / 46.2 MB

2024-09-03 18:11 UTC, SandraBabirye commented on conf/modules.config
> +            saveAs: { filename -> filename.equals('versions.yml') ? null : filename }
Hi @tkchafin , Thankyou for suggestion however my output file should be with name as  'meta.id.csv ' as per the description of the issue #121.

2024-09-04 10:26 UTC, BethYates commented on subworkflows/local/annotation_statistics.nf
I think line 33 should be `ch_versions = ch_versions.mix ( AGAT_SPSTATISTICS.out.versions.first() )`

2024-09-04 13:03 UTC, merged