Public dev merged
sanger-tol/genomenote pull request #68
Opened 2023-06-07 14:50 UTC by BethYates

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomenote/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-06-07 14:52 UTC, BethYates commented
This is the merge of the dev branch into the public-dev branch. I've also added the genome metadata sub workflow into the main pipeline

2023-06-09 10:34 UTC, priyanka-surana requested changes
I am yet to test the pipeline. But so far it looks good. Some minor comments and a general suggestion – can we simplify this parameter name `genome_metadata_file_template`?

2023-06-15 14:38 UTC, BethYates commented on README.md
> +- [Matthieu Muffato](https://github.com/muffato)
Done

2023-06-15 14:38 UTC, BethYates commented on conf/test_full.config
Yes, changes added.

2023-06-15 14:39 UTC, BethYates commented on workflows/genomenote.nf
> +
Changes made

2023-06-15 14:42 UTC, BethYates commented on workflows/genomenote.nf
> +
Changes made

2023-06-20 14:08 UTC, priyanka-surana approved these changes
Looks good. We can work on CITATIONS, etc. closer to release. Thank you for making the changes.

2023-06-20 16:29 UTC, merged