Genome metadata added module to produce a docx file from a genome note template file and genome metadata parameter file
sanger-tol/genomenote pull request #70
Opened 2023-06-27 17:24 UTC by BethYates

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomenote/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-06-29 21:14 UTC, muffato commented on modules/local/populate_template.nf
> +    container "frostasm/python-docx-template"
I would recommend making our own container (hosted on quay.io) with just the Conda package docxtpl=0.11.5. This way, we have the guarantee that the version of `docxtpl` is exactly 0.11.5. This also isolates us from 1) the Docker image being updated (even if it's unlikely), 2) the download limits that Docker is imposing (which could prevent Nextflow from downloading this container)

2023-06-30 08:19 UTC, priyanka-surana requested changes
Discussed with Beth – this PR is to add only the consistent csv to the template. 
- Why does the subworkflow not emit anything? Also nothing is published in the results folder. Is the note document created not needed outside the pipeline?

2023-06-30 12:15 UTC, muffato commented on modules/local/populate_template.nf
> +        note.docx
We tend to name all output files using the same stem, typically the assembly ID. Can you introduce the task prefix thing like in the other modules and name the output `${prefix}.docx` ?

2023-06-30 12:18 UTC, BethYates commented on subworkflows/local/genome_metadata.nf
> +    ch_all_params.view()
No, line now removed but will go in as part of next set of commits as this file has code changes that aren't ready to be commited yet

2023-06-30 12:19 UTC, BethYates commented on modules/local/populate_template.nf
> +    path("note.docx"), emit: file_path_inconsistent
I meant to change this, it's now populated_genome_note_template

2023-06-30 12:28 UTC, muffato commented on modules/local/populate_template.nf
> +    path("note.docx"), emit: file_path_inconsistent
Or just "genome_note" to keep it short :) ?

2023-06-30 12:37 UTC, BethYates commented on modules/local/populate_template.nf
> +    container "frostasm/python-docx-template"
Container created and added to quay.io

2023-06-30 12:47 UTC, BethYates commented on modules/local/populate_template.nf
> +    path("note.docx"), emit: file_path_inconsistent
ok, just genome_note :)

2023-06-30 13:55 UTC, BethYates commented on modules/local/populate_template.nf
> +        note.docx
Yes, this is something I should do here I should be passing some metadata info (GCA) through to this module and to some of the others in this subworkflow. I've not made this change yet but it will go in as part of the next set of changes

2023-06-30 15:24 UTC, muffato commented on modules/local/populate_template.nf
> +        note.docx
At the module level, just add `meta` and base the name off `task.ext.prefix`/`meta.id`. `meta.id` is the only key that is mandatory, and it is expected to contain the right ID for that piece of data. The module doesn't explicitly assume / expect this ID to be an accession number, that's up to the main workflow to decide how to set `meta.id` in the first place. And actually, in some pipelines or test runs, `meta.id` may actually be an assembly name like _mMelMel3.1_ or something derived like _mMelMel3.1_subset_

2023-07-12 16:24 UTC, BethYates commented on modules/local/populate_template.nf
> +        note.docx
Changes made

2023-07-18 09:03 UTC, priyanka-surana requested changes
Some suggestions on standardising code. Take what works for you.

2023-07-18 09:03 UTC, priyanka-surana commented on modules/local/populate_template.nf
> +    val(meta)
Why is `meta` by itself, and not with one of the inputs?

2023-07-18 09:03 UTC, priyanka-surana commented on modules/local/populate_template.nf
> +    path(filename_out), emit: genome_note
Similarly, no `meta` in output?

2023-07-18 13:24 UTC, BethYates commented on docs/output.md
> +  </details>
change made, sorry I hadn't realised the distinction

2023-07-18 13:25 UTC, BethYates commented on modules/local/populate_template.nf
> +    filename_out = "${prefix}.docx"
change made, I think I was following an example from another of the tol pipelines which used prefix this way

2023-07-18 13:25 UTC, BethYates commented on subworkflows/local/genome_metadata.nf
> +    POPULATE_TEMPLATE( ch_assembly_metadata, ch_all_params, ch_note_template)
change made

2023-07-18 13:26 UTC, BethYates commented on modules/local/populate_template.nf
> +    val(meta)
I've changed this so meta is included with the channel containing the list of files to be parsed

2023-07-21 07:22 UTC, priyanka-surana approved these changes

2023-07-21 07:55 UTC, priyanka-surana commented
The tests are failing but go ahead and merge. The error is due to `FASTK_FASTK`, this is an ongoing issue with how it works with `scratch` space. I have a ticket to work on this next sprint.

2023-07-21 08:05 UTC, merged